#激活不同环境的配置文件
spring:
  profiles:
    active: dev

logging:
  level:
    root: info
    com.example.emos.wx.db.dao: debug
    org.mybatis: debug
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"